"""empty message

Revision ID: 56f72f60a32b
Revises: 
Create Date: 2019-10-06 15:24:31.747333

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f72f60a32b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Enum('SUPERUSER', 'USER', name='rolenames'), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_created'), 'roles', ['created'], unique=False)
    op.create_index(op.f('ix_roles_deleted'), 'roles', ['deleted'], unique=False)
    op.create_index(op.f('ix_roles_modified'), 'roles', ['modified'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('ya_disc_token', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_created'), 'users', ['created'], unique=False)
    op.create_index(op.f('ix_users_deleted'), 'users', ['deleted'], unique=False)
    op.create_index(op.f('ix_users_modified'), 'users', ['modified'], unique=False)
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    accounts_table = sa.sql.table(
        'roles',
        sa.sql.column('id', sa.Integer),
        sa.sql.column('name', sa.Enum),
        sa.sql.column('description', sa.String),
        sa.sql.column('created', sa.DateTime),
        sa.sql.column('modified', sa.DateTime),
    )
    op.bulk_insert(accounts_table, [
        {'name': 'SUPERUSER', 'description': 'Superuser', 'created': datetime.now(), 'modified': datetime.now()},
        {'name': 'USER', 'description': 'Regular user', 'created': datetime.now(), 'modified': datetime.now()},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_index(op.f('ix_users_modified'), table_name='users')
    op.drop_index(op.f('ix_users_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_created'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_modified'), table_name='roles')
    op.drop_index(op.f('ix_roles_deleted'), table_name='roles')
    op.drop_index(op.f('ix_roles_created'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
